#ifndef AIRWAVES_CONST_PARAMETER_PROJECTOR
#define AIRWAVES_CONST_PARAMETER_PROJECTOR

#include "ofMain.h"

const int cWINDOW_WIDTH = 1353;
const int cWINDOW_HEIGHT = 1024;

#endif // !AIRWAVES_CONST_PARAMETER_PROJECTOR